apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            kubernetesAPIEndpoints:
              type: object
              properties:
                serverEndpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      clientCIDR:
                        type: string
                        pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
                      serverAddress:
                        type: string
                        pattern: '^(((http:\/\/|https:\/\/)?)((?=.{1,255}$)[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?(?:\.[0-9A-Za-z](?:(?:[0-9A-Za-z]|-){0,61}[0-9A-Za-z])?)*\.?))(:(102[4-9]|10[3-9]\d|1[1-9]\d{2}|[2-9]\d{3}|[1-5]\d{4}|6[0-4]\d{3}|65[0-4]\d{2}|655[0-2]\d|6553[0-5]))?$'
            caBundle:
                type: byte
                pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
            authInfo:
              type: object
              properties:
                providers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      type:
                        type: object
                        properties:
                          name:
                            type: string
                      config:
                        type: array
                        items:
                          type: object
                          properties:
                            key:
                              type: string
                            value:
                              type: string
