apiVersion: v1
kind: List
items:

# to delegate authentication and authorization
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: auth-delegator-clusterregistry-admission
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:auth-delegator
  subjects:
  - kind: ServiceAccount
    namespace: clusterregistry-admission
    name: server

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
    name: system:openshift:online:clusterregistry-admission-server
  rules:
  - apiGroups:
    - online.openshift.io
    resources:
    - clusters
    verbs:
    - get
    - list
    - watch

# to let aggregated apiservers create admission reviews
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: system:openshift:online:clusterregistry-admission-requester
  rules:
  - apiGroups:
    - admission.online.openshift.io
    resources:
    - clusters
    verbs:
    - create

# to let the admission server read the namespace reservations
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: clusterregistry-admission-server-clusterregistry-admission
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: system:openshift:online:clusterregistry-admission-server
  subjects:
  - kind: ServiceAccount
    namespace: clusterregistry-admission
    name: server

# to read the config for terminating authentication
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    namespace: kube-system
    name: extension-server-authentication-reader-clusterregistry-admission
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: extension-apiserver-authentication-reader
  subjects:
  - kind: ServiceAccount
    namespace: clusterregistry-admission
    name: server

