required = [
"k8s.io/code-generator/cmd/client-gen",
"github.com/kubernetes/repo-infra/verify/boilerplate/test",
]

# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

ignored = [
  "github.com/kubernetes/repo-infra/kazel",
]

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"
